### PR TITLE
updated readme file

### PR DESCRIPTION
**Pull request by AKG1301**

### CODE REVIEW

**Comment by AKG1301** [comment]
please see last file only

**Comment by AKG1301** [comment]
MAINTAINERS NEED TO ADD THE HACKTOBERFEST TOPIC TO THE REPOSITORY, OR ADD THE HACKTOBERFEST-ACCEPTED LABEL TO YOUR PR/MR.

**Comment by itsmeShC** [comment]
Done

**Comment by AKG1301** [comment]
Thankyou

**Pull request merged**
